# Generated by Django 5.2.4 on 2025-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_galleryimage_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='confirmed', max_length=100, null=True),
        ),
    ]
