# Generated by Django 5.2.4 on 2025-10-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
    ]
