# Generated by Django 5.2.4 on 2025-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_images_image_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.CharField(default='101', max_length=10),
        ),
    ]
