# Generated by Django 5.2.4 on 2025-10-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
