name: Rosentic Scan
on:
  pull_request:
    branches: ["**"]

jobs:
  rosentic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Rosentic Action
        uses: Rosentic/rosentic-action@v1
